# coding: utf-8

"""
    Data Space Connector service

    This connector requests data from the data layer and provides a REST API for servicing requests from the catalog service.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_connector.api.data_product_api import DataProductApi


class TestDataProductApi(unittest.TestCase):
    """DataProductApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataProductApi()

    def tearDown(self) -> None:
        pass

    def test_get_data_product(self) -> None:
        """Test case for get_data_product

        Get a data product details
        """
        pass

    def test_get_data_products(self) -> None:
        """Test case for get_data_products

        Get a list of data products
        """
        pass


if __name__ == '__main__':
    unittest.main()
