# coding: utf-8

"""
    Data Space Connector service

    This connector requests data from the data layer and provides a REST API for servicing requests from the catalog service.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_connector.models.data_product import DataProduct

class TestDataProduct(unittest.TestCase):
    """DataProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataProduct:
        """Test DataProduct
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataProduct`
        """
        model = DataProduct()
        if include_optional:
            return DataProduct(
                id = '',
                name = '',
                size = 56,
                mimetype = '',
                digest = '',
                tags = [
                    ds_connector.models.tag.Tag(
                        text = '', )
                    ],
                source = None,
                links = {
                    'key' : ''
                    }
            )
        else:
            return DataProduct(
                id = '',
                name = '',
                size = 56,
                mimetype = '',
                digest = '',
                tags = [
                    ds_connector.models.tag.Tag(
                        text = '', )
                    ],
                source = None,
                links = {
                    'key' : ''
                    },
        )
        """

    def testDataProduct(self):
        """Test DataProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
