openapi: 3.1.0
info:
  title: Data Space Connector service
  description: This connector requests data from the data layer and provides a REST
    API for servicing requests from the catalog service.
  contact:
    name: HIRO-MicroDataCenters
    email: all-hiro@hiro-microdatacenters.nl
  license:
    name: MIT
    url: https://github.com/HIRO-MicroDataCenters-BV/ds-connector/blob/main/LICENSE
  version: 0.1.1
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health-check/:
    get:
      summary: Health check
      description: Returns a 200 status code if the service is up and running
      operationId: health_check
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /data-products/:
    get:
      tags:
      - Data product
      summary: Get a list of data products
      description: Returns a list of data products with the ability to paginate
      operationId: get_data_products
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          default: 1
          title: Page
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          default: 100
          title: Pagesize
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResult'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /data-products/{connector_id}/{data_product_id}/:
    get:
      tags:
      - Data product
      summary: Get a data product details
      description: Returns an information about the data product
      operationId: get_data_product
      parameters:
      - name: connector_id
        in: path
        required: true
        schema:
          type: string
          title: Connector Id
      - name: data_product_id
        in: path
        required: true
        schema:
          type: string
          title: Data Product Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProduct'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Connector:
      properties:
        id:
          type: string
          title: Id
          examples:
          - connector1
      type: object
      required:
      - id
      title: Connector
    DataProduct:
      properties:
        id:
          type: string
          title: Id
        name:
          type: string
          title: Name
        size:
          type: integer
          title: Size
        mimetype:
          type: string
          title: Mimetype
        digest:
          type: string
          title: Digest
        tags:
          items:
            $ref: '#/components/schemas/Tag'
          type: array
          title: Tags
        source:
          additionalProperties:
            anyOf:
            - $ref: '#/components/schemas/Connector'
            - $ref: '#/components/schemas/Interface'
          type: object
          title: Source
        _links:
          additionalProperties:
            type: string
          type: object
          title: ' Links'
      type: object
      required:
      - id
      - name
      - size
      - mimetype
      - digest
      - tags
      - source
      - _links
      title: DataProduct
      examples:
      - _links:
          accessPoint: /connector1/interface1/8D8AC610-566D-4EF0-9C22-186B2A5ED793/
        digest: 1df50e8ad219e34f0b911e097b7b588e31f9b435
        id: 8D8AC610-566D-4EF0-9C22-186B2A5ED793
        mimetype: text/plain
        name: cancer_data_2024
        size: 1024
        source:
          connector:
            id: connector1
          interface:
            id: interface1
        tags:
        - text: tag1
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthCheck:
      properties:
        status:
          type: string
          title: Status
          examples:
          - OK
      type: object
      required:
      - status
      title: HealthCheck
    Interface:
      properties:
        id:
          type: string
          title: Id
          examples:
          - interface1
      type: object
      required:
      - id
      title: Interface
    PaginatedResult:
      properties:
        page:
          type: integer
          title: Page
          examples:
          - 1
        size:
          type: integer
          title: Size
          examples:
          - 100
        items:
          items:
            $ref: '#/components/schemas/DataProduct'
          type: array
          title: Items
      type: object
      required:
      - page
      - size
      - items
      title: PaginatedResult
    Tag:
      properties:
        text:
          type: string
          title: Text
          examples:
          - tag1
      type: object
      required:
      - text
      title: Tag
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
